CourseField/urls.py
from django.contrib import admin
from django.urls import path, include
import apps

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.courses.urls'), name='courses'),
]

apps/courses/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from CourseField import settings
from . import views


app_name = 'courses'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:course_pk>/lesson/<int:lesson_pk>/', views.LessonDetailView.as_view(), name='lesson-detail'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/courses/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    index_num = models.IntegerField()
    media = models.FileField(upload_to='media/', blank=True, null=True)
    cover = models.ImageField(upload_to='media/covers/', blank=False, default='https://dummyimage.com/400x225')
    total_time = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', args=[str(self.course.id), str(self.id)])

    def get_media_url(self):
        return self.media.url


class Course(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    instructor = models.CharField(max_length=100)
    cover = models.ImageField(upload_to='media/covers/', blank=True, null=True)
    course_path = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:course-detail', args=[str(self.id)])


class Category(models.Model):
    name = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return self.name

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from apps.courses.models import Course, Lesson


# Create your models here.



class User(AbstractUser):
    pass


class PlayHistory(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True)
    time = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)

apps/courses/views.py
import json

from django.http import HttpResponse, JsonResponse

from django.shortcuts import render
from django.views import View
from apps.courses.models import Course, Lesson
from apps.users.models import User, PlayHistory


# Create your views here.
class IndexView(View):
    def get(self, request):
        course_list = Course.objects.all()
        context = {'course_list': course_list}

        from .auto_importer import get_course_media
        get_course_media()
        return render(request, 'courses/index.html', context)


class CourseDetailView(View):
    def get(self, request, pk):
        course = Course.objects.get(pk=pk)
        from .auto_importer import add_lesson
        add_lesson(course)
        context = {'lesson_list': course.lesson_set.all(), 'course': course}
        return render(request, 'courses/course_detail.html', context)


class LessonDetailView(View):
    def get(self, request, course_pk, lesson_pk):
        lesson = Lesson.objects.get(pk=lesson_pk)
        play_history = PlayHistory.objects.filter(lesson=lesson, user=request.user).first()
        if play_history:
            play_time = play_history.time
        else:
            play_time = 0
        print(play_time)

        context = {'lesson': lesson, 'play_time': play_time}
        return render(request, 'courses/lesson_detail.html', context)

    def post(self, request, course_pk, lesson_pk):
        # print the post data
        print(json.loads(request.body))
        play_time = json.loads(request.body)['time']

        PlayHistory.objects.update_or_create(
            lesson=Lesson.objects.get(pk=lesson_pk),
            user=User.objects.get(id=request.user.id),
            defaults={'time': play_time}
        )

        return JsonResponse({'status': 'ok'}, status=200)

apps/users/views.py
from django.shortcuts import render

# Create your views here.

templates/courses/base.html
<!doctype html>
{% load static %}

<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CourseField {% block head_title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/output.css' %}" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />
      
      
<script>
    
    if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
        document.documentElement.classList.add('dark');
    } else {
        document.documentElement.classList.remove('dark')
    }
    
</script>

  </head>
  <body>
  <div class="text-sm text-gray-900">
      <nav class="flex items-center px-4 py-3 bg-white justify-between shadow">
          <div class="text-gray-900 space-x-6">
                <a class="font-bold flex items-center space-x-6" href="{% url 'courses:index' %} ">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 3.75V16.5L12 14.25 7.5 16.5V3.75m9 0H18A2.25 2.25 0 0 1 20.25 6v12A2.25 2.25 0 0 1 18 20.25H6A2.25 2.25 0 0 1 3.75 18V6A2.25 2.25 0 0 1 6 3.75h1.5m9 0h-9" />
                </svg>
                    CourseField</a>
          </div>
            <div class="text-gray-900">
                
            </div>
      </nav>
  </div>
  {% block content %}
  {% endblock %}
  {% block scripts %}
  {% endblock %}
  </body>
</html>

templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block head_title %}{% endblock %}

{% block content %}
</div>
<div class="container mx-auto px-4 py-8">
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-5">
{% for lesson in lesson_list %}

      <!-- 课程卡片1 -->
      <div class="bg-white shadow-lg rounded-lg overflow-hidden max-w-sm hover:shadow-2xl">
      <a class="" href="{{ lesson.get_absolute_url }}">
        <img class="w-full h-48 object-cover" src="/{{ lesson.cover }}" alt="课程1图片">
        <div class="p-4">
          <h2 class="text-lg font-bold mb-2">{{ lesson.title }}</h2>
          <p class="text-gray-700 text-sm">课程描述信息...</p>
          <!-- 这里可以添加更多课程相关信息，如讲师、日期等 -->
        </div>
        </a>
      </div>


{% endfor %}
</div>
</div>
{% endblock %}

templates/courses/index.html
{% extends 'courses/base.html' %}

{% block content %}
    
<div class="container mx-auto px-4 py-8">
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-5">
{% for course in course_list %}

      <!-- 课程卡片1 -->
      <div class="bg-white shadow-lg rounded-lg overflow-hidden max-w-sm hover:shadow-2xl">
      <a class="" href="{{ course.get_absolute_url }}">
        <img class="w-full h-48 object-cover" src="https://dummyimage.com/421x261" alt="课程1图片">
        <div class="p-4">
          <h2 class="text-lg font-bold mb-2">{{ course.title }}</h2>
          <p class="text-gray-700 text-sm">课程描述信息...</p>
          <!-- 这里可以添加更多课程相关信息，如讲师、日期等 -->
        </div>
        </a>
      </div>


{% endfor %}
</div>
</div>
{% endblock %}

templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block head_title %}- {{ lesson.title }}{% endblock %}

{% block content %}
<div class="container px-4">
<h2 class="text-2xl font-bold">{{ lesson.title }}</h2>
    <div class="flex justify-center">
        <div class="w-5/6">
                <video id="player" playsinline controls >
                  <source src="{{ lesson.media.url }}" type="video/mp4" />
                </video>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
    <script src="https://cdn.plyr.io/3.7.8/plyr.polyfilled.js"></script>
<script>
const player = new Plyr('#player');

window.onload = function() {
    
    player.currentTime = {{ play_time }};
    console.log('Current time:', player.currentTime);
}

function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        let cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            let cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

let csrftoken = getCookie('csrftoken');

let url = '{{ lesson.get_absolute_url }}';

function postData(url = '', data = {}) {
    return fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrftoken
        },
        body: JSON.stringify(data)
    })
    .then(response => response.json());
}

// print current time on play every 10 seconds 
setInterval(() => {
    console.log('Current time:', player.currentTime);
    let data = {
        user: '{{ request.user.id }}',
        lesson: '{{ lesson.id }}',
        time: player.currentTime};
    
    postData(url, data)
        .then(data => {
            console.log(data);
        });
}, 10000);

player.on('pause', event => {
    console.log('Video paused', player.currentTime);
});
</script>
{% endblock %}